language: cpp
dist: bionic
compiler: gcc

script: 
  # Build
  - qmake
  - make release
  # Run
  - ./travis_qmake_gcc_cpp14_gprof
  # produce the gprof log
  - gprof travis_qmake_gcc_cpp14_gprof > gprof.log
  # Read the 100 top lines
  - head gprof.log -n 1000